databases:
  - name: youandme_db
    databaseName: youandme_db
    user: youandme
    region: singapore

services:
  - type: web
    name: youandme
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:postgres://youandme_db_user:DL6WHLVSG80ERNHR5xlRvZnTsEdpv8QL@dpg-cgbhb2hmbg55nqmanumg-a/youandme_db
      - key: DATABASE_URL
        fromDatabase:
          name: youandme_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
